name: Checks

on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker compose build

      - name: Test
        run: docker compose run --rm app python manage.py test

      - name: Lint
        run: docker compose run --rm app flake8
